// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nniadcxfnvrzdjsfyvdi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5uaWFkY3hmbnZyemRqc2Z5dmRpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2MDU2NjgsImV4cCI6MjA2NDE4MTY2OH0.Hf2kRcQQ9m2O8gbyYBN6WXH6531C7Xw2bQvhDzwBCh4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);